services:
  db_sync:
    build: 
      context: ..
      dockerfile: for_docker/Dockerfile
    volumes:
      # Link your Python_SQL folder so the DB file is saved locally
      - ..:/app
      
      # DYNAMIC PATH: Automatically grabs the current Windows user's folder!
      - "${USERPROFILE}/OneDrive - Femtonics Kft/Documents - 2pteam/Tables:/app/data:ro"
      
    environment:
      # These tell the script where to find things inside the container's logic
      - EXCEL_SOURCE=/app/data/Injection diary.xlsx
      - DB_DESTINATION=/app/injection_diary.db